Repository samvera/hyku, pull requests merged in 2023-06, with the labels that each got.

#1936 fix-hyku-demo-deploy
  ops/demo-deploy.tmpl.yaml
Labels: ignore-for-release

#1950 Adds code comment and reverts a rubocop change that breaks theming
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/controllers/hyrax/contact_form_controller.rb
  app/controllers/hyrax/homepage_controller.rb
  app/controllers/hyrax/pages_controller.rb
Labels: bug, technical debt, patch-ver

#1951 Copyright year
  app/views/shared/_footer.html.erb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
Labels: patch-ver

#1937 update-bin-web-script-for-analytics
  bin/web
Labels: minor-ver

#1948 🐛 Addressing Psych::DisallowedClass error with YAML changes
  config/application.rb
Labels: patch-ver

#1957 update color labels and help text
  app/assets/stylesheets/hyku.scss
  app/forms/hyrax/forms/admin/appearance.rb
  app/helpers/application_helper.rb
  app/views/hyrax/admin/appearances/_color_input.html.erb
  app/views/shared/_appearance_styles.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/locales/it.yml
  config/locales/pt-BR.yml
  config/locales/zh.yml
  spec/views/hyrax/admin/appearances/show.html.erb_spec.rb
Labels: patch-ver
