Repository samvera/hyku, pull requests merged in 2023-02, with the labels that each got.

#1907 upgrade to hyrax 3.5, make graph indexer on by default
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  app/controllers/hyrax/dashboard/collections_controller.rb
  app/jobs/reindex_collections_job.rb
  config/initializers/hyrax.rb
  docker-compose.yml
Labels: minor-ver

#1906 adjust importer section of readme, bump ruby/rails versions
  README.md
Labels: documentation, ignore-for-release

#1908 Yarn lock had git+ssh which doesnt work in certain situations
  yarn.lock
Labels: ignore-for-release

#1913 refactor CollectionPresenterDecorator to use #decorate
  app/presenters/hyrax/collection_presenter_decorator.rb
  app/services/group_aware_role_checker.rb
Labels: patch-ver

#1915 i526-add-gha-cool-titles
  .github/workflows/base.yaml
  .github/workflows/build-test-lint.yaml
  .github/workflows/deploy.yaml
Labels: ignore-for-release

#1921 update Hyku::VERSION to 5.0.1
  config/initializers/version.rb
Labels: ignore-for-release

#1918 bring back a production worthy docker-compose example
  docker-compose.production.yml
Labels: patch-ver
