Repository samvera/hyku, pull requests merged in 2023-04, with the labels that each got.

#1933 upgrade hyrax docker image and remove malloc env var.
  Dockerfile
  lib/tasks/reset.rake
Labels: patch-ver

#1934 Extended oai
  config/application.rb
  lib/oai/provider/metadata_format/hyku_dublin_core.rb
  lib/oai/provider/model_decorator.rb
  lib/oai/provider/response/list_metadata_formats_decorator.rb
  spec/features/oai_pmh_spec.rb
Labels: minor-ver

#1935 rubocop fixes
  lib/oai/provider/metadata_format/hyku_dublin_core.rb
  lib/oai/provider/model_decorator.rb
  lib/oai/provider/response/list_metadata_formats_decorator.rb
  spec/features/oai_pmh_spec.rb
Labels: ignore-for-release

#1939 upgrade to bulkrax 5.2
  Gemfile.lock
  config/initializers/bulkrax.rb
Labels: minor-ver

#1943 install pry-byebug
  Gemfile
  Gemfile.lock
Labels: ignore-for-release

#1942 Iiif av
  Gemfile
  Gemfile.lock
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/helpers/shared_search_helper.rb
  app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
  app/presenters/hyku/work_show_presenter.rb
  app/presenters/hyrax/iiif_manifest_presenter_decorator.rb
  app/services/hyrax/manifest_builder_service_decorator.rb
  config/initializers/file_set_derivatives_overrides.rb
  config/initializers/hyrax.rb
  config/initializers/iiif_print.rb
  config/routes.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/presenters/hyku/work_show_presenter_spec.rb
  spec/presenters/hyrax/iiif_manifest_presenter/display_image_presenter_spec.rb
  spec/presenters/hyrax/iiif_manifest_presenter_spec.rb
Labels: minor-ver

#1945 update iiif-print
  Gemfile.lock
Labels: patch-ver
