Repository samvera/hyku, pull requests merged in 2023-11, with the labels that each got.

#2037 🎁 Superadmins can activate users
  .env
  app/controllers/admin/users_controller.rb
  app/views/hyrax/admin/users/index.html.erb
  config/locales/de.yml
  config/locales/devise_invitable.de.yml
  config/locales/devise_invitable.es.yml
  config/locales/devise_invitable.fr.yml
  config/locales/devise_invitable.it.yml
  config/locales/devise_invitable.pt-BR.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/hyrax.de.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/locales/it.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.zh.yml
  config/locales/zh.yml
  config/routes.rb
  ops/demo-deploy.tmpl.yaml
  ops/iiif-deploy.tmpl.yaml
  ops/iiif.tmpl.yaml
  ops/review-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
  spec/controllers/admin/users_controller_spec.rb
Labels: Repository feature, minor-ver

#2021 🐛 Fix duplicating slider icons in IR theme
  app/views/layouts/application.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_resource_type_slider.html.erb
Labels: minor-ver

#2038 remove duplicate JAVA_OPTS env var
  .env
Labels: patch-ver

#2040 Collection service backport
  app/controllers/hyrax/my/works_controller_decorator.rb
Labels: patch-ver

#2041 make iiif print off by default so we can mark it as an experimental feature
  app/models/generic_work.rb
  app/models/image.rb
Labels: minor-ver
