Repository samvera/hyku, pull requests merged in 2023-12, with the labels that each got.

#2044 pin-json-canonicalization-0.3.1
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2045 commit-schema-updates
  db/schema.rb
Labels: patch-ver

#2007 ♻️ Introduce Hyku::Application.theme_view_path_roots
  app/controllers/concerns/hyrax/works_controller_behavior.rb
  app/controllers/hyrax/contact_form_controller.rb
  app/controllers/hyrax/pages_controller.rb
  config/application.rb
Labels: minor-ver

#2056 🧹 Remove deprecated Blacklight code
  app/controllers/hyrax/contact_form_controller.rb
  app/controllers/hyrax/homepage_controller.rb
  app/controllers/hyrax/pages_controller.rb
  app/controllers/search_history_controller.rb
Labels: patch-ver

#2059 ♻️ Hyrax 5 refactor homepage presenter
  app/presenters/hyrax/homepage_presenter.rb
  app/presenters/hyrax/homepage_presenter_decorator.rb
Labels: patch-ver

#2060 🧹 Hyrax 5 catalog controller and specs
  app/controllers/catalog_controller.rb
  spec/controllers/catalog_controller_spec.rb
Labels: major-ver

#2062 🧹 Hyrax 5 get additional specs passing
  .circleci/config.yml
  app/models/concerns/account_settings.rb
  spec/rails_helper.rb
  spec/support/fixtures.rb
Labels: major-ver

#2063 Hyrax 5 upgrade db migrations
  db/migrate/20231215215705_create_hyrax_counter_metrics.hyrax.rb
  db/migrate/20231215215706_change_work_id_to_string.hyrax.rb
  db/migrate/20231215215707_add_indices_to_hyrax_counter_metrics.hyrax.rb
  db/migrate/20231215215708_add_fields_to_counter_metric.hyrax.rb
  db/schema.rb
Labels: major-ver

#2064 🧹 Fix Hyrax 5 remaining controller spec failures
  config/initializers/active_fedora_override.rb
  spec/controllers/hyrax/generic_works_controller_spec.rb
  spec/controllers/hyrax/images_controller_spec.rb
Labels: major-ver

#2067 🧹 Hyrax 5 upgrade additional specs
  .rubocop.yml
  app/controllers/hyrax/contact_form_controller.rb
  app/controllers/hyrax/pages_controller.rb
  app/models/role.rb
  app/services/roles_service.rb
  lib/stanford/importer/purl_retriever.rb
  spec/abilities/collection_ability_spec.rb
  spec/abilities/solr_document_ability_spec.rb
  spec/factories/collections.rb
  spec/forms/hyrax/forms/permission_template_form_spec.rb
  spec/jobs/create_default_admin_set_job_spec.rb
  spec/lib/importer/mods_importer_spec.rb
  spec/lib/stanford/importer/purl_parser_spec.rb
  spec/services/roles_service_spec.rb
Labels: major-ver

#2069 🧹 Clean up a couple blacklight views
  app/helpers/blacklight/blacklight_helper_behavior.rb.old
  app/helpers/hyku/blacklight_helper_behavior.rb
  app/helpers/hyrax_helper.rb
  app/views/catalog/_index_header.html.erb
  app/views/catalog/_index_masonry_default.html.erb
Labels: patch-ver

#2070 Update hyrax double combo
  Gemfile.lock
Labels: major-ver

#2072 🧹 Remove copied code
  app/models/hyrax/group.rb
  app/services/hyrax/workflow/permission_query.rb
  spec/models/hyrax/group_spec.rb
  spec/services/hyrax/workflow/permission_query_spec.rb
Labels: major-ver

#2071 More spec fixes
  app/helpers/application_helper.rb
  spec/presenters/hyku/menu_presenter_spec.rb
Labels: major-ver

#2074 🐛 Ensure :maxFileSize is integer
  app/models/concerns/account_settings.rb
Labels: major-ver

#2075 Skip taking a picture on failure
  spec/rails_helper.rb
Labels: patch-ver

#2076 🧹 Fix issue regarding Valkyrie::Identifier
  config/initializers/hyrax.rb
Labels: patch-ver

#2077 🧹 Favor Sipity::Entity function over to_sipity_entity
  spec/requests/work_approval_permissions_spec.rb
Labels: minor-ver

#2081 🤖 Specify Cache Root
  .circleci/config.yml
Labels: ignore-for-release

#2082 🧹 Update spec to reflect AdminSet default behavior
  spec/services/create_account_spec.rb
Labels: ignore-for-release

#2080 Hyrax 5 upgrade remove site roles
  app/controllers/roles_controller.rb
  app/views/roles/index.html.erb
  config/routes.rb
  spec/controllers/roles_controller_spec.rb
  spec/features/roles_spec.rb
  spec/routing/roles_routing_spec.rb
Labels: major-ver

#2085 🤖 Fix spec/features/collection_type_spec.rb
  spec/features/collection_type_spec.rb
Labels: ignore-for-release

#2084 Remove stanford importer
  .dockerignore
  README.md
  app/jobs/import_work_from_purl_job.rb
  bin/extract_mods_to_spreadsheet
  bin/import_from_csv
  bin/import_from_purl
  bin/import_mods_files
  lib/importer.rb
  lib/importer/csv_importer.rb
  lib/importer/csv_parser.rb
  lib/importer/factory.rb
  lib/importer/factory/collection_factory.rb
  lib/importer/factory/etd_factory.rb
  lib/importer/factory/image_factory.rb
  lib/importer/factory/object_factory.rb
  lib/importer/factory/string_literal_processor.rb
  lib/importer/factory/with_associated_collection.rb
  lib/importer/log_subscriber.rb
  lib/importer/mods_importer.rb
  lib/importer/mods_parser.rb
  lib/stanford.rb
  lib/stanford/importer.rb
  lib/stanford/importer/mods_parser.rb
  lib/stanford/importer/purl_parser.rb
  lib/stanford/importer/purl_retriever.rb
  spec/fixtures/mods/shpc/druid_xv169dn4538.mods
  spec/fixtures/mods/shpc/kx532cb7981.mods
  spec/fixtures/purl/bc390xk2647.xml
  spec/jobs/import_work_from_purl_job_spec.rb
  spec/lib/importer/csv_importer_spec.rb
  spec/lib/importer/csv_parser_spec.rb
  spec/lib/importer/factory/etd_factory_spec.rb
  spec/lib/importer/factory/image_factory_spec.rb
  spec/lib/importer/factory/string_literal_processor_spec.rb
  spec/lib/importer/mods_importer_spec.rb
  spec/lib/importer/mods_parser_spec.rb
  spec/lib/stanford/importer/mods_parser_spec.rb
  spec/lib/stanford/importer/purl_parser_spec.rb
  spec/support/shared_examples_for_csv_importer.rb
Labels: major-ver

#2086 Lock chromedriver version
  .circleci/config.yml
Labels: major-ver

#2088 🧹 Clean up model overrides
  app/models/ability.rb
  app/models/concerns/hyrax/ability/collection_ability.rb
  app/models/concerns/hyrax/ability/solr_document_ability.rb
  app/models/content_block.rb
  app/models/hydra/access_controls/embargo_decorator.rb
  app/models/hydra/access_controls/lease_decorator.rb
  app/models/hyrax/collection_type_participant_decorator.rb
  app/models/hyrax/contact_form.rb
  app/models/hyrax/contact_form_decorator.rb
  app/models/hyrax/group.rb
  app/models/hyrax/permission_template_access_decorator.rb
Labels: patch-ver

#2091 🧹 Restore btn-sign-up on splash page
  app/assets/stylesheets/hyku.scss
  app/views/splash/index.html.erb
Labels: patch-ver

#2092 🧹 Fix `./spec/requests/admin_dashboard_spec.rb` spec
  app/forms/hyrax/forms/workflow_responsibility_form_decorator.rb
  app/forms/hyrax/forms/workflow_responsibility_group_form.rb
Labels: patch-ver

#2090 🧹 Clean up actors
  app/actors/hyrax/environment_decorator.rb
  spec/actors/hyrax/environment_decorator_spec.rb
Labels: patch-ver

#2093 🎁 Upgrade Redis initializer to Hyrax 5's gen version
  config/initializers/redis_config.rb
  spec/features/admin_dashboard_spec.rb
Labels: patch-ver

#2095 🐛 Handle missing labels
  app/controllers/identity_providers_controller.rb
  app/views/hyrax/dashboard/sidebar/_configuration.html.erb
  app/views/identity_providers/_form.html.erb
  app/views/identity_providers/index.html.erb
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/it.yml
  config/locales/pt-BR.yml
  config/locales/zh.yml
Labels: major-ver

#2094 🧹 Assigning collection_type
  spec/views/hyrax/dashboard/collections/_form_share.erb_spec.rb
Labels: major-ver

#2096 Fixing nav link selectors to new structure
  spec/views/admin/groups/edit.html.erb_spec.rb
  spec/views/admin/groups/new.html.erb_spec.rb
Labels: major-ver

#2097 Fixing nav link selectors to new structure
  spec/views/admin/groups/remove.html.erb_spec.rb
Labels: major-ver

#2105 🧹 Allow :clean or :clean_repo to work for the cleaners
  spec/rails_helper.rb
Labels: patch-ver

#2102 🧹 Fix button class for Bootstrap 3 to 4
  spec/features/admin_set_form_participants_tab_spec.rb
Labels: patch-ver

#2106 🧹 The selector is not working
  spec/features/cultural_repository_theme_spec.rb
  spec/jobs/create_default_admin_set_job_spec.rb
Labels: patch-ver

#2108 🧹 Ensure feature specs run clean
  spec/rails_helper.rb
Labels: patch-ver

#2110 Hyrax 5 upgrade with adventist dev
  .env
  app/controllers/catalog_controller.rb
  app/search_builders/adv_search_builder.rb
  spec/search_builders/adv_search_builder_spec.rb
Labels: minor-ver

#2111 🧹 Attempting to find and squash bug
  Gemfile
  Gemfile.lock
  app/models/user.rb
Labels: patch-ver

#2109 🧹 Clean up services
  app/services/hyrax/admin_set_create_service_decorator.rb
  app/services/hyrax/collection_types/create_service_decorator.rb
  app/services/hyrax/collections/permissions_create_service_decorator.rb
  app/services/hyrax/indexes_thumbnails.rb
  app/services/hyrax/indexes_thumbnails_decorator.rb
  app/services/hyrax/manifest_builder_service_decorator.rb
  app/services/hyrax/permission_manager_decorator.rb
  app/services/hyrax/quick_classification_query.rb
  app/services/hyrax/quick_classification_query_decorator.rb
  app/services/hyrax/thumbnail_path_service.rb
  app/services/hyrax/thumbnail_path_service_decorator.rb
  app/services/hyrax/work_thumbnail_path_service.rb
  app/services/hyrax/work_thumbnail_path_service_decorator.rb
  config/application.rb
  spec/services/hyrax/collection_types/create_service_decorator_spec.rb
  spec/services/hyrax/indexes_thumbnails_decorator_spec.rb
  spec/services/hyrax/quick_classification_query_decorator_spec.rb
  spec/services/hyrax/thumbnail_path_service_spec.rb
  spec/services/hyrax/work_thumbnail_path_service_decorator_spec.rb
Labels: patch-ver

#2115 Prime hyrax 5 upgrade refactor for pals
  app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
  config/application.rb
  spec/config/application_spec.rb
Labels: patch-ver
