Repository samvera/hyku, pull requests merged in 2023-10, with the labels that each got.

#2005 ⚙️ Add bundle as part of docker-compose
  docker-compose.yml
Labels: patch-ver

#2010 ♻️ Add handling for Knapsack theme overrides
  app/controllers/hyrax/admin/appearances_controller.rb
  config/application.rb
Labels: minor-ver

#2012 ♻️ Favor Hyku::Application.path_for over Rails.root
  app/services/uploaded_collection_thumbnail_path_service.rb
  app/views/hyrax/dashboard/collections/_current_thumbnail.html.erb
Labels: minor-ver

#2009 :bug: subject can't be blank for the contact form
  app/controllers/hyrax/contact_form_controller.rb
Labels: patch-ver

#2019 🐛 Add custom rendering for license
  .rubocop.yml
  app/services/uploaded_collection_thumbnail_path_service.rb
  app/views/records/show_fields/_license.html.erb
Labels: patch-ver

#2020 ♻️ Add option to override devise configuration
  app/models/user.rb
  config/application.rb
  spec/config/application_spec.rb
Labels: minor-ver

#2014 :bug: font inputs rendered twice fix
  app/assets/javascripts/admin_font_select.js
  app/assets/javascripts/application.js
Labels: minor-ver

#2022 run asset build later in process to allow knapsack to run it only one time
  Dockerfile
Labels: minor-ver

#2023 🐛 Fix Add to Collection for page 2+ of works
  app/controllers/hyrax/my/works_controller_decorator.rb
Labels: patch-ver

#2025 Inviting existing users fails
  app/controllers/hyku/invitations_controller.rb
  spec/controllers/hyku/invitations_controller_spec.rb
Labels: patch-ver

#2027 🧹 Update contact email descriptions
  config/initializers/hyrax.rb
  config/locales/simple_form.en.yml
Labels: minor-ver

#2003 upgrade bulkrax to 5.4.0
  Gemfile.lock
Labels: minor-ver

#2029 🐛 Change Hyky to Hyku
  app/views/hyrax/dashboard/collections/_current_thumbnail.html.erb
Labels: bug, patch-ver

#2031 :bug: Correct contact_email and contact_email_to descriptions
  config/locales/simple_form.de.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.zh.yml
Labels: bug, patch-ver

#2032 :bug: Fix depositor role issue
  app/models/concerns/hyrax/ability/work_ability.rb
  spec/features/create_work_spec.rb
Labels: bug, patch-ver
