Repository samvera/hyku, pull requests merged in 2023-09, with the labels that each got.

#1983 startup on windows
  README.md
Labels: documentation, ignore-for-release

#1976 SSO Interface and Setup for SAML, OpenID Connect and CAS
  .gitguardian.yaml
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/assets/stylesheets/single_signon.scss
  app/controllers/identity_providers_controller.rb
  app/controllers/single_signon_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/models/concerns/account_settings.rb
  app/models/identity_provider.rb
  app/models/user.rb
  app/uploaders/logo_uploader.rb
  app/views/_user_util_links.html.erb
  app/views/devise/omniauth_callbacks/complete.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/hyrax/dashboard/sidebar/_configuration.html.erb
  app/views/identity_providers/_form.html.erb
  app/views/identity_providers/edit.html.erb
  app/views/identity_providers/index.html.erb
  app/views/identity_providers/new.html.erb
  app/views/shared/_footer.html.erb
  app/views/single_signon/index.html.erb
  config/application.rb
  config/initializers/apartment.rb
  config/initializers/devise.rb
  config/initializers/is_it_working.rb
  config/locales/en.yml
  config/locales/hyrax.en.yml
  config/routes.rb
  db/migrate/20230131202855_create_iiif_print_pending_relationships.iiif_print.rb
  db/migrate/20230727180717_add_omniauth_to_users.rb
  db/migrate/20230804073106_create_identity_providers.rb
  db/schema.rb
  docker-compose.yml
  lib/omni_auth/strategies/saml_decorator.rb
  spec/factories/identity_providers.rb
  spec/models/identity_provider_spec.rb
  spec/requests/single_signon_request_spec.rb
Labels: minor-ver

#1972 Sidekiq jobs dashboard improvements
  app/models/user.rb
  config/routes.rb
Labels: minor-ver

#1970 Bulkrax importing work
  .env
  .github/workflows/base.yaml
  Dockerfile
  Gemfile
  Gemfile.lock
  config/database.yml
  config/initializers/bulkrax.rb
  docker-compose.yml
Labels: minor-ver

#1986 account elevator clear especially when on proprieter view
  app/middleware/account_elevator.rb
Labels: minor-ver

#1990 view updates for devise from adventist
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_links.html.erb
Labels: minor-ver

#1991 make indexing records more resiliant and uniform
  app/jobs/application_job.rb
  app/jobs/reindex_collections_job.rb
  app/jobs/reindex_file_sets_job.rb
  app/jobs/reindex_item_job.rb
  app/jobs/reindex_works_job.rb
  lib/tasks/index.rake
Labels: minor-ver

#1988 make sure layers are flattened to fix pdf tripple issue
  lib/hydra/derivatives/processors/image_decorator.rb
Labels: minor-ver

#1987 use partent title instead of filename in uv
  lib/iiif_manifest/manifest_builder/canvas_builder_decorator.rb
Labels: minor-ver

#1992 Schemas and timeouts
  config/database.yml
  config/fedora.yml
  config/initializers/active_fedora_override.rb
  config/initializers/apartment.rb
  lib/active_fedora/solr_service_decorator.rb
  lib/tasks/db_enhancements.rake
  lib/wings/services/custom_queries/find_ids_by_model_decorator.rb
Labels: minor-ver

#1995 register and add missing methods to avoid content block errors
  app/controllers/catalog_controller.rb
  app/controllers/hyrax/content_blocks_controller_decorator.rb
  app/controllers/hyrax/homepage_controller_decorator.rb
  app/models/content_block.rb
  app/models/generic_work.rb
  lib/wings/services/custom_queries/find_ids_by_model_decorator.rb
Labels: minor-ver

#1989 ability to mark during importing for actor stack
  app/actors/hyrax/environment.rb
  app/factories/bulkrax/object_factory_decorator.rb
Labels: minor-ver

#1999 User invite email has html tag
  config/locales/devise_invitable.de.yml
  config/locales/devise_invitable.en.yml
  config/locales/devise_invitable.es.yml
  config/locales/devise_invitable.fr.yml
  config/locales/devise_invitable.it.yml
  config/locales/devise_invitable.pt-BR.yml
  config/locales/devise_invitable.zh.yml
Labels: bug, patch-ver
