Repository samvera/hyku, pull requests merged in 2024-01, with the labels that each got.

#2118 🧹 Change locale file load order so that our local files are prioritized
  config/application.rb
Labels: patch-ver

#2119 🧹 Update IIIF Print and AV gems
  Gemfile
  Gemfile.lock
  ops/exiftool_image_to_fits.xslt
Labels: patch-ver

#2120 🐛 Fix video thumbnail generation
  app/services/hyrax/file_set_derivatives_service_decorator.rb
Labels: patch-ver

#2121 🧹 Update Hyku version
  config/initializers/version.rb
Labels: patch-ver

#2122 Hyrax 5 fix css
  app/assets/javascripts/hyrax/app.js.erb
  app/assets/stylesheets/hyku.scss
  app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb
  app/views/hyrax/dashboard/works/_list_works.html.erb
  app/views/hyrax/homepage/_home_content.html.erb
  app/views/hyrax/my/works/_list_works.html.erb
  spec/rails_helper.rb
Labels: patch-ver

#2125 🧹 Update `rails` to `6-1-stable` for GoodJob
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2127 Hyrax 5 upgrade pr feedback
  config/initializers/apartment.rb
  docker-compose.bundle.yml
Labels: patch-ver

#2126 🧹 Addresses Hyrax 5 PR feedback: Rubocop Naming/PredicateName errors
  app/controllers/application_controller.rb
  app/controllers/proprietor/users_controller.rb
  app/models/hyrax/group.rb
  app/models/user.rb
  app/services/group_aware_role_checker.rb
  app/services/hyrax/workflow/permission_grantor.rb
  app/views/proprietor/users/_form.html.erb
  app/views/proprietor/users/index.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/models/hyrax/group_spec.rb
Labels: major-ver

#2130 I35 valkyrize hyku wings
  Gemfile.lock
  app/models/solr_endpoint.rb
  app/services/hyrax/custom_queries/find_by_bulkrax_identifier.rb
  app/services/wings/custom_queries/find_by_bulkrax_identifier.rb
  config/initializers/wings.rb
  db/migrate/20240104192407_enable_uuid_extension.valkyrie_engine.rb
  db/migrate/20240104192408_create_orm_resources.valkyrie_engine.rb
  db/migrate/20240104192409_add_model_type_to_orm_resources.valkyrie_engine.rb
  db/migrate/20240104192410_change_model_type_to_internal_model.valkyrie_engine.rb
  db/migrate/20240104192411_create_path_gin_index.valkyrie_engine.rb
  db/migrate/20240104192412_create_internal_resource_index.valkyrie_engine.rb
  db/migrate/20240104192413_create_updated_at_index.valkyrie_engine.rb
  db/migrate/20240104192414_add_optimistic_locking_to_orm_resources.valkyrie_engine.rb
  db/schema.rb
  lib/hyrax/solr_service_decorator.rb
Labels: patch-ver

#2134 🧹 Remove basic_metadata.yaml
  Gemfile.lock
  config/metadata/basic_metadata.yaml
Labels: patch-ver

#2136 🐛 Proprietor page solr service fix
  lib/hyrax/solr_service_decorator.rb
Labels: patch-ver

#2137 update version to 6.0.0rc1
  config/initializers/version.rb
Labels: patch-ver

#2133 🤖 Update charts for deploy
  bin/helm_deploy
  ops/demo-deploy.tmpl.yaml
  ops/iiif-deploy.tmpl.yaml
  ops/review-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: patch-ver

#2140 🎁 fixes to unblock deploys
  app/controllers/saved_searches_controller.rb
  config/storage.yml
Labels: patch-ver

#2145 working on fixing redis deploy
  ops/demo-deploy.tmpl.yaml
Labels: ignore-for-release

#2139 knapsack gemfile additions or replacement
  Gemfile
  Gemfile.lock
Labels: minor-ver

#2152 🧹 Specify knapsack required branch
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2143 WIP to get collections & admin sets working
  app/forms/roles_form_decorator.rb
  app/models/generic_work_resource.rb
  app/models/hyrax/administrative_set_decorator.rb
  app/models/hyrax/pcdm_collection_decorator.rb
  app/models/image_resource.rb
  app/views/hyrax/dashboard/collections/_form_discovery.html.erb
  config/initializers/hyrax.rb
Labels: major-ver

#2149 I35 valkyrize hyku routes and redirects
  .env
  app/controllers/hyrax/generic_work_resources_controller.rb
  app/controllers/hyrax/image_resources_controller.rb
  app/helpers/hyku_helper.rb
  app/presenters/hyrax/generic_work_resource_presenter.rb
  app/presenters/hyrax/image_resource_presenter.rb
  app/views/hyrax/base/_show_actions.html.erb
  app/views/hyrax/dashboard/collections/_show_document_list_row.html.erb
  app/views/hyrax/dashboard/works/_list_works.html.erb
  app/views/hyrax/homepage/_featured_fields.html.erb
  app/views/hyrax/homepage/_recent_document.html.erb
  app/views/hyrax/my/works/_list_works.html.erb
  config/routes.rb
  ops/demo-deploy.tmpl.yaml
  ops/iiif-deploy.tmpl.yaml
  ops/iiif.tmpl.yaml
  ops/review-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: patch-ver

#2158 I903 remove bulkrax_identifier dependency
  app/indexers/collection_indexer.rb
  app/indexers/concerns/hyku_indexing.rb
  app/services/hyrax/custom_queries/find_by_bulkrax_identifier.rb
  app/services/wings/custom_queries/find_by_bulkrax_identifier.rb
  config/initializers/wings.rb
  spec/services/hyrax/custom_queries/find_by_bulkrax_identifier_spec.rb
Labels: patch-ver

#2160 ♻️ Favor Hyrax::SolrService
  app/models/solr_endpoint.rb
  config/initializers/hyrax.rb
  config/initializers/riiif.rb
  lib/wings/services/custom_queries/find_ids_by_model_decorator.rb
  spec/features/collection_spec.rb
  spec/features/oai_pmh_spec.rb
  spec/models/account_spec.rb
  spec/models/solr_endpoint_spec.rb
  spec/rails_helper.rb
  spec/requests/catalog_controller_spec.rb
Labels: patch-ver

#2159 🧹 Make the appropriate link generate
  app/indexers/concerns/hyku_indexing.rb
  app/models/concerns/hyrax/solr_document_behavior_decorator.rb
  app/models/generic_work_resource.rb
  app/models/image_resource.rb
  spec/models/concerns/hyrax/solr_document_behavior_decorator_spec.rb
Labels: patch-ver
