Repository samvera/hyku, pull requests merged in 2024-02, with the labels that each got.

#2161 🧹 Fix relationship links
  app/indexers/concerns/hyku_indexing.rb
  app/models/solr_document.rb
Labels: patch-ver

#2141 override gems from knapsack
  .gitignore
  Gemfile
  bundler.d/.gitkeep
Labels: minor-ver

#2163 remove HYKU_IIIF_PRINT conditional
  app/models/generic_work.rb
  app/models/generic_work_resource.rb
  app/models/image.rb
  app/models/image_resource.rb
Labels: patch-ver

#2164 Collection & Admin Set Valkyrization
  app/forms/admin_set_resource_form.rb
  app/forms/collection_resource_form.rb
  app/forms/hyrax/forms/admin/administrative_set_form_decorator.rb
  app/forms/hyrax/forms/collection_form_decorator.rb
  app/helpers/shared_search_helper.rb
  app/indexers/admin_set_resource_indexer.rb
  app/indexers/collection_resource_indexer.rb
  app/models/admin_set_resource.rb
  app/models/collection_resource.rb
  app/models/hyrax/pcdm_collection_decorator.rb
  app/services/roles_service.rb
  app/views/hyrax/admin/users/index.html.erb
  config/initializers/hyrax.rb
  config/initializers/wings.rb
  config/metadata/collection_resource.yaml
  spec/forms/admin_set_resource_spec.rb
  spec/forms/collection_resource_form_spec.rb
  spec/indexers/admin_set_resource_indexer_spec.rb
  spec/indexers/collection_resource_indexer_spec.rb
  spec/models/admin_set_resource_spec.rb
  spec/models/collection_resource_spec.rb
Labels: major-ver
