Repository samvera/hyku, pull requests merged in 2024-09, with the labels that each got.

#2310 Migration script for collections
  app/jobs/migrate_resources_job.rb
  config/initializers/hyrax.rb
  lib/tasks/index.rake
  spec/jobs/migrate_resources_job_spec.rb
Labels: patch-ver

#2311 :broom: [i1020] - ga4 follow up
  Gemfile.lock
  app/assets/stylesheets/hyku.scss
  app/jobs/depositor_email_notification_job.rb
  app/mailers/hyku_mailer.rb
  app/views/hyku_mailer/depositor_email.html.erb
  app/views/hyrax/base/_download_pdf.html.erb
  spec/jobs/depositor_email_notification_job_spec.rb
Labels: patch-ver

#2312 Update WillowSword gem
  Gemfile.lock
Labels: patch-ver

#2313 Adjust themes
  app/assets/stylesheets/hyku.scss
  app/views/hyrax/homepage/_featured_collection_section.html.erb
  app/views/themes/cultural_repository/_collections_section.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_recent_document.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_recently_uploaded.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_recently_uploaded.html.erb
Labels: patch-ver

#2314 Include bulkrax metadata in resource forms and indexers
  Gemfile.lock
  app/forms/etd_resource_form.rb
  app/forms/oer_resource_form.rb
  app/indexers/etd_resource_indexer.rb
  app/indexers/oer_resource_indexer.rb
Labels: ignore-for-release

#2317 flesh out ability to find jobs in various background job tools
  lib/active_job_tenant.rb
Labels: ignore-for-release

#2316 🐛 Fix "Sort by: Published Date"
  app/indexers/concerns/hyku_indexing.rb
  app/models/sort_title.rb
Labels: bug, patch-ver

#2324 dont stop app start if goodjobs tables are not created yet
  config/application.rb
Labels: patch-ver

#2326 prevent loosing permissions on collection / admin set migration
  app/jobs/migrate_resources_job.rb
Labels: patch-ver

#2325 handle exception if date is not in date format
  app/helpers/hyrax_helper.rb
Labels: patch-ver

#2327 🐛 Moves HykuIndexing to CollectionResourceIndexer
  app/indexers/collection_resource_indexer.rb
  app/models/collection_resource.rb
Labels: patch-ver

#2330 ⚙️ Update Bulkrax + run migration
  Gemfile.lock
  db/schema.rb
Labels: patch-ver

#2329 I769 snippets
  app/controllers/catalog_controller.rb
  app/indexers/concerns/hyku_indexing.rb
  app/indexers/hyku/indexers/file_set_indexer.rb
  config/initializers/hyrax.rb
  spec/fixtures/pdf/pdf_sample.pdf
  spec/indexers/hyku/indexers/file_set_indexer_spec.rb
Labels: minor-ver

#2331 persist banners, logos and thumbnails for collection migration
  Gemfile.lock
  app/jobs/migrate_resources_job.rb
  app/models/collection_resource.rb
  config/metadata/with_thumbnail.yaml
  db/schema.rb
Labels: patch-ver

#2328 [i777] - collection metadata clean up
  app/assets/stylesheets/hyrax.scss
  app/helpers/application_helper.rb
  spec/features/create_etd_spec.rb
  spec/helpers/application_helper_spec.rb
Labels: patch-ver

#2334 🧹 Updates version of order-already gem
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2336 Clean up viewer logic
  Gemfile
  Gemfile.lock
  app/presenters/hyku/work_show_presenter.rb
  app/views/hyrax/base/_relationships.html.erb
  app/views/hyrax/base/_representative_media.html.erb
  app/views/themes/image_show/hyrax/base/show.html.erb
Labels: ignore-for-release

#2337 🐛 Change `link_to_search` to `link_to_facet`
  app/controllers/catalog_controller.rb
Labels: patch-ver

#2339 fix moderate security warning
  Gemfile.lock
Labels: patch-ver

#2338 Support s3 file storage
  Gemfile
  Gemfile.lock
  app/jobs/migrate_resources_job.rb
  app/services/migrate_resource_service.rb
  config/initializers/wings.rb
  docs/configuration.md
  lib/reprocessor.rb
  spec/jobs/migrate_resources_job_spec.rb
Labels: minor-ver

#2341 💄 Removes the multiple indicator from Solr suffix
  app/controllers/catalog_controller.rb
  app/indexers/concerns/hyku_indexing.rb
Labels: patch-ver

#2345 Public facing collections show page styling
  app/assets/javascripts/application.js
  app/assets/javascripts/blacklight_gallery.js
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/hyrax.scss
  app/views/hyrax/collections/show.html.erb
Labels: patch-ver

#2346 Fix universal viewer duplicates
  Gemfile
  Gemfile.lock
  app/indexers/concerns/hyku_indexing.rb
  app/presenters/hyrax/iiif_manifest_presenter_decorator.rb
Labels: patch-ver
