Repository samvera/hyku, pull requests merged in 2024-04, with the labels that each got.

#2173 Valkyrize Reindex jobs
  app/controllers/sites_controller.rb
  app/jobs/reindex_admin_sets_job.rb
  app/jobs/reindex_collections_job.rb
  app/jobs/reindex_file_sets_job.rb
  app/jobs/reindex_item_job.rb
  app/jobs/reindex_works_job.rb
Labels: bug, patch-ver

#2174 📚 Remove completed TODO item
  lib/tasks/index.rake
Labels: patch-ver

#2175 remove sentry dependencies
  Gemfile.lock
Labels: patch-ver

#2176 🐛 Fix PDF.js for Valkyrie
  Gemfile.lock
  app/forms/generic_work_resource_form.rb
  app/forms/image_resource_form.rb
  app/helpers/pdf_js_helper.rb
  app/listeners/hyrax_listener.rb
  app/models/concerns/pdf_behavior.rb
  app/presenters/hyku/work_show_presenter.rb
  app/views/hyrax/file_sets/media_display/_pdf.html.erb
  config/metadata/with_pdf_viewer.yaml
  spec/rails_helper.rb
Labels: minor-ver

#2179 🐛 Fix solr endpoint default issue
  lib/hyrax/solr_service_decorator.rb
  spec/requests/catalog_controller_spec.rb
Labels: bug, patch-ver

#2182 Fixes more solr uri issues
  lib/valkyrie/indexing/solr/indexing_adapter_decorator.rb
Labels: patch-ver

#2190 the generate_work_url method from iiif print does not want a hash
  app/views/catalog/_index_gallery_collection_wrapper.html.erb
  app/views/catalog/_index_header_list_collection.html.erb
  app/views/catalog/_thumbnail_list_collection.html.erb
  app/views/hyrax/homepage/_recent_document.html.erb
  app/views/themes/cultural_repository/hyrax/homepage/_recent_document.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_recent_document.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb
Labels: patch-ver

#2189 Update grapher.rb
  lib/hyrax/transactions/grapher.rb
Labels: ignore-for-release

#2191 Update Bulkrax for Embargo/Lease import support
  Gemfile.lock
  db/schema.rb
Labels: ignore-for-release

#2195 I2194 address pr feedback and then some
  app/controllers/application_controller.rb
  app/indexers/concerns/hyrax/location_indexer_decorator.rb
  app/models/concerns/bulkrax/has_matchers_decorator.rb
  app/models/nil_site.rb
  app/views/_head_tag_extras.html.erb
  app/views/hyrax/homepage/_recent_document.html.erb
  config/environments/production.rb
  lib/tasks/sidekiq.rake
  public/favicon.ico
  spec/controllers/hyrax/homepage_controller_spec.rb
  spec/features/create_work_spec.rb
Labels: patch-ver

#2196 🎁 Install and configure Willow Sword gem
  Gemfile
  Gemfile.lock
  config/initializers/willow_sword.rb
  config/routes.rb
Labels: patch-ver

#2197 🎁 Add `ActiveJob::Scheduler`
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2198 Fix specs
  Gemfile
  app/jobs/prune_stale_guest_users_job.rb
Labels: patch-ver
