Repository samvera/hyku, pull requests merged in 2024-11, with the labels that each got.

#2375 update hyrax for chunked uploads bug fix
  Gemfile.lock
Labels: ignore-for-release

#2376 Update hyrax
  Gemfile.lock
Labels: ignore-for-release

#2377 update iiif_print for image progessing bug fix
  Gemfile.lock
Labels: ignore-for-release

#2378 make iiif_print and s3 backed valkyrie storage play nicely together
  Gemfile.lock
  config/initializers/wings.rb
Labels: patch-ver

#2379 Update Hyrax and IIIF Print
  Gemfile.lock
Labels: ignore-for-release

#2381 [i886] - update logic to fix collection thumbnail bug
  app/services/hyrax/thumbnail_path_service_decorator.rb
  config/environments/production.rb
  spec/services/hyrax/thumbnail_path_service_spec.rb
Labels: patch-ver, reindex required

#2384 Add per-tenant Bulkrax field mappings
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css
  app/models/concerns/account_settings.rb
  app/views/proprietor/accounts/edit.html.erb
  app/views/shared/_settings.html.erb
  config/initializers/assets.rb
  lib/bulkrax/bulkrax_decorator.rb
  spec/lib/bulkrax/bulkrax_decorator_spec.rb
  spec/models/concerns/account_settings_spec.rb
Labels: minor-ver

#2386 Small fixes for views & branding
  app/controllers/hyrax/dashboard/collections_controller_decorator.rb
  app/presenters/hyrax/presenter_renderer_decorator.rb
  app/views/hyrax/oers/_attribute_rows.html.erb
  app/views/themes/cultural_show/hyrax/oers/_related_item.html.erb
  app/views/themes/cultural_show/hyrax/oers/show.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_recent_document.html.erb
  config/authorities/discipline.yml
  spec/services/hyrax/discipline_service_spec.rb
Labels: patch-ver

#2391 Prevent field mappings set value from bleeding into other specs
  spec/lib/bulkrax/bulkrax_decorator_spec.rb
Labels: patch-ver

#2390 UI improvements
  app/assets/stylesheets/hyrax.scss
  app/views/hyrax/collections/_collection_description.html.erb
  app/views/hyrax/collections/show.html.erb
  app/views/hyrax/homepage/_recent_document.html.erb
Labels: minor-ver
