Repository samvera/hyku, pull requests merged in 2024-08, with the labels that each got.

#2269 Update Hyrax
  Gemfile.lock
Labels: patch-ver

#2270 🐛 Remove outdated blacklight_range_limit partial
  app/controllers/concerns/blacklight/controller_decorator.rb
  app/views/blacklight_range_limit/_range_limit_panel.html.erb
Labels: patch-ver

#2271 ⚙️ Turn off autocomplete in Rails console
  .irbrc
  spec/models/featured_collection_list_spec.rb
Labels: patch-ver

#2272 :broom: locks rails to a version that supports good jobs
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2273 Remove migrate collection thumbnails rake
  lib/tasks/migrate_hyku_commons_collection_thumbnails_to_valkyrie.rake
  spec/tasks/migrate_hyku_commons_collection_thumbnails_to_valkyrie_spec.rb
Labels: patch-ver

#2251 update the reprocessor
  lib/reprocessor.rb
Labels: patch-ver

#2275 More theme updates
  app/assets/stylesheets/themes/cultural_repository.scss
  app/assets/stylesheets/themes/institutional_repository.scss
  app/assets/stylesheets/themes/neutral_repository.scss
  app/views/themes/cultural_repository/_logo.html.erb
  app/views/themes/institutional_repository/_logo.html.erb
  app/views/themes/institutional_repository/layouts/homepage.html.erb
Labels: patch-ver

#2274 add missing authorities
  config/initializers/hyrax.rb
Labels: minor-ver

#2276 ⚙️ Add condition for `Valkyrie::MetadataAdapter`
  config/initializers/wings.rb
Labels: patch-ver

#2277 ⬆️ Update Hyrax
  Gemfile.lock
Labels: patch-ver

#2278 ♻️ Introduce the `Hyku::Forms::Admin::Appearance`
  app/controllers/hyrax/admin/appearances_controller_decorator.rb
  app/forms/hyku/forms/admin/appearance.rb
  app/views/shared/_appearance_styles.html.erb
  spec/forms/hyku/forms/admin/appearance_spec.rb
  spec/views/hyku/admin/appearances/show.html.erb_spec.rb
Labels: patch-ver

#2280 bump hyrax to fix analytics issues
  Gemfile.lock
Labels: patch-ver

#2281 🧹 Move Appearance#default_values public
  app/forms/hyku/forms/admin/appearance.rb
  app/listeners/hyrax_listener.rb
Labels: patch-ver

#2282 🧹 update bulkrax version
  Gemfile.lock
  db/schema.rb
Labels: minor-ver

#2284 Themes logic refactor
  app/controllers/concerns/hyku/home_page_themes_behavior.rb
  app/controllers/hyrax/contact_form_controller_decorator.rb
  app/controllers/hyrax/homepage_controller.rb
  app/controllers/hyrax/pages_controller_decorator.rb
  config/application.rb
  spec/controllers/concerns/hyku/home_page_themes_behavior_spec.rb
Labels: patch-ver

#2283 🧹 updates rubocop and adds rubocop-factory_bot
  .rubocop.yml
  .rubocop_fixme.yml
  .rubocop_todo.yml
  Gemfile
  Gemfile.lock
  app/controllers/hyrax/dashboard/collections_controller_decorator.rb
  app/helpers/blacklight/catalog_helper_behavior_decorator.rb
  app/models/concerns/pdf_behavior.rb
  app/models/featured_collection_list.rb
  app/models/sushi.rb
  app/models/sushi/item_report.rb
  app/models/sushi/platform_report.rb
  app/models/sushi/platform_usage_report.rb
  app/models/sushi/report_list.rb
  app/services/iiif_print/tenant_config.rb
  app/services/import_counter_metrics.rb
  lib/tasks/tenantize_task.rake
  spec/features/admin_set_form_participants_tab_spec.rb
  spec/features/appearance_theme_spec.rb
  spec/features/create_generic_work_spec.rb
  spec/features/create_image_spec.rb
  spec/features/work_editor_role_spec.rb
  spec/models/sushi_spec.rb
  spec/models/uploaded_file_spec.rb
  spec/routing/featured_collections_route_spec.rb
Labels: patch-ver

#2286 update bundler inject message to be more accurate
  Gemfile
Labels: ignore-for-release

#2287 💄 Fix the gradient on featured works on homepage
  app/assets/stylesheets/hyku.scss
Labels: patch-ver

#2290 ⬆️ Update WillowSword
  Gemfile.lock
Labels: patch-ver

#2291 Dashboard styling
  app/assets/stylesheets/hyku.scss
  app/views/hyrax/dashboard/sidebar/_configuration.html.erb
Labels: patch-ver

#2288 simplify per tenant recurring jobs, make sure they stay running by checking them every night
  app/jobs/batch_email_notification_job.rb
  app/jobs/depositor_email_notification_job.rb
  app/jobs/embargo_auto_expiry_job.rb
  app/jobs/lease_auto_expiry_job.rb
  app/jobs/tenant_maintenance_job.rb
  app/models/account.rb
  app/services/create_account.rb
  config/application.rb
  lib/active_job_tenant.rb
  spec/jobs/batch_email_notification_job_spec.rb
  spec/jobs/depositor_email_notification_job_spec.rb
  spec/jobs/embargo_auto_expiry_job_spec.rb
  spec/jobs/lease_auto_expiry_job_spec.rb
  spec/jobs/tenant_maintenance_job_spec.rb
  spec/services/create_account_spec.rb
Labels: minor-ver

#2292 Fix Admin Set form to make edit work
  app/forms/admin_set_resource_form.rb
Labels: patch-ver

#2183 ⚙️ Pinning DerivativeRodeo to a better version
  Gemfile
  Gemfile.lock
Labels: ignore-for-release

#2203 fix redis caching per tenant
  app/models/account.rb
  config/locales/simple_form.en.yml
  spec/models/account_spec.rb
Labels: patch-ver

#2300 Update Bulkrax
  Gemfile.lock
Labels: patch-ver

#2295 Subdomains to exclude
  app/models/concerns/account_cname.rb
  app/models/domain_name.rb
Labels: minor-ver

#2289 User stats job gets run daily
  app/jobs/user_stat_collection_job.rb
  app/models/account.rb
  spec/jobs/user_stat_collection_job_spec.rb
  spec/services/create_account_spec.rb
Labels: minor-ver

#2301 :bug: incorrect path prevents thumbnails from rendering
  app/services/hyrax/thumbnail_path_service_decorator.rb
Labels: patch-ver

#2304 Update bulkrax to fix adventist ingesting
  Gemfile.lock
Labels: ignore-for-release

#2302 Batch Email Notifications
  app/jobs/batch_email_notification_job.rb
  app/models/sushi.rb
  app/models/user.rb
  app/models/user_batch_email.rb
  db/migrate/20240820195641_remove_last_emailed_at_from_users.rb
  db/migrate/20240820200440_create_user_batch_emails.rb
  db/schema.rb
  spec/jobs/batch_email_notification_job_spec.rb
Labels: patch-ver

#2308 Update bulkrax
  Gemfile.lock
Labels: ignore-for-release
