Repository samvera/hyku, pull requests merged in 2024-06, with the labels that each got.

#2230 :bug: Correct thumbnail_path_ss solr index value
  app/indexers/collection_resource_indexer.rb
  app/services/hyrax/indexes_thumbnails_decorator.rb
Labels: patch-ver

#2233 move to github actions instead of circleci
  .circleci/config.yml
  .github/workflows/build-test-lint.yaml
  .github/workflows/build.yml
Labels: ignore-for-release

#2231 allow use of Google Analytics 4
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/hyku.scss
  app/views/hyrax/file_sets/_actions.html.erb
  app/views/shared/_ga4.html.erb
  config/analytics.yml
Labels: minor-ver

#2234 Update bulkrax
  Gemfile.lock
Labels: minor-ver

#2235 :bug: [i37] - Fix syntax error on contact page
  app/views/hyrax/contact_form/new.html.erb
Labels: patch-ver

#2238 :bug: Fix collection search & facet
  app/controllers/catalog_controller.rb
  app/views/hyrax/homepage/_featured_collection_section.html.erb
Labels: patch-ver

#2210 I350 Derivatives & Update IiifPrint
  Dockerfile
  Gemfile
  Gemfile.lock
  app/models/ability.rb
  app/models/concerns/hyrax/solr_document_behavior_decorator.rb
  app/services/iiif_print/tenant_config.rb
  app/views/hyrax/file_sets/_actions.html.erb
  config/initializers/iiif_print.rb
  db/migrate/20240214005253_add_model_details_to_iiif_print_pending_relationships.iiif_print.rb
  docker-compose.bundle.yml
  docker-compose.override-nodory.yml
  docker-compose.production.yml
  docker-compose.yml
  spec/fixtures/derivatives/00-xml.xml
  spec/fixtures/derivatives/b6-thumbnail.jpeg
  spec/indexers/generic_work_resource_indexer_spec.rb
  spec/indexers/image_resource_indexer_spec.rb
  spec/models/concerns/hyrax/solr_document_behavior_decorator_spec.rb
  spec/models/hyrax/file_set_decorator_spec.rb
Labels: major-ver

#2239 Fix gallery and masonry catalog search results
  Gemfile
  Gemfile.lock
  app/controllers/catalog_controller.rb
Labels: patch-ver

#2240 🐛 Break long links in catalog search
  app/assets/stylesheets/hyrax.scss
Labels: patch-ver

#2241 Some frontend fixes
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/themes/institutional_repository.scss
  app/views/blacklight_range_limit/_range_limit_panel.html.erb
  app/views/hyrax/admin/users/index.html.erb
  app/views/themes/neutral_repository/layouts/_share_your_work_row.html.erb
  config/locales/hyrax.de.yml
  config/locales/hyrax.en.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
Labels: patch-ver

#2242 I205 collection thumbnail rework
  Dockerfile
  bin/web
Labels: patch-ver

#2243 Update iiif print to 2.0.1
  Gemfile.lock
Labels: ignore-for-release

#2244 Branding fixes
  app/controllers/hyrax/dashboard/collections_controller_decorator.rb
  app/helpers/application_helper.rb
  app/presenters/hyrax/collection_presenter_decorator.rb
  app/services/hyrax/thumbnail_path_service_decorator.rb
  app/views/hyrax/collections/_media_display.html.erb
  app/views/hyrax/collections/show.html.erb
  app/views/hyrax/dashboard/collections/_list_collections.html.erb
  app/views/hyrax/my/collections/_list_collections.html.erb
  lib/hyrax/transactions/steps/save_collection_banner_decorator.rb
Labels: patch-ver

#2236 :bug: [i51] Fix for collection sharing bug
  app/views/hyrax/dashboard/collections/_form_share.html.erb
Labels: patch-ver

#2246 Update gems
  Gemfile.lock
  app/listeners/hyrax_listener.rb
Labels: ignore-for-release

#2248 🐛 Wrap quotes around ENV var
  app/views/shared/_ga4.html.erb
Labels: patch-ver

#2250 Update gems
  Gemfile.lock
Labels: ignore-for-release

#2249 🐛 Bring over CsvParserDecorator fix from Pals
  app/parsers/bulkrax/csv_parser_decorator.rb
  spec/parsers/bulkrax/csv_parser_decorator_spec.rb
Labels: patch-ver

#2247 🐛 [i70] - Removes Show PDF options as form input fields
  config/metadata/with_pdf_viewer.yaml
Labels: patch-ver

#2252 🐛 Fix Add Child link
  app/views/hyrax/base/_show_actions.html.erb
Labels: patch-ver

#2253 🐛 Ensure `Hyku::Transactions` is loaded
  lib/hyrax/transactions/container_decorator.rb
Labels: patch-ver

#2256 :broom: Update iiif print
  Gemfile.lock
Labels: ignore-for-release

#2254 Fix duplicate thumbnails for PDFs
  app/services/hyrax/file_set_derivatives_service_decorator.rb
Labels: patch-ver

#2257 Update Bulkrax
  Gemfile.lock
Labels: patch-ver

#2259 🐛 Fix Bulkrax issues for Knapsack applications
  app/parsers/bulkrax/csv_parser_decorator.rb
  config/initializers/bulkrax.rb
  spec/parsers/bulkrax/csv_parser_decorator_spec.rb
Labels: patch-ver
