Repository samvera/hyku, pull requests merged in 2024-12, with the labels that each got.

#2392 Fixes invalid method error in IR theme
  app/controllers/hyrax/contact_form_controller_decorator.rb
  app/controllers/hyrax/pages_controller_decorator.rb
Labels: patch-ver

#2394 Added slideshow start info back in from blacklight.
  app/assets/stylesheets/hyku.scss
  app/views/hyrax/collections/show.html.erb
  config/locales/en.yml
Labels: patch-ver

#2397 Bulkrax chunked uploads pipeline fix
  Gemfile
  Gemfile.lock
  docker-compose.yml
  spec/features/appearance_theme_spec.rb
  spec/features/create_etd_spec.rb
  spec/features/create_generic_work_spec.rb
  spec/features/create_image_spec.rb
  spec/features/create_oer_spec.rb
  spec/features/work_editor_role_spec.rb
Labels: minor-ver

#2370 Update bulkrax for chunked upload support
  Gemfile
  Gemfile.lock
Labels: minor-ver

#2393 Fix incorrectly colored save button
  app/views/hyrax/pages/_form.html.erb
  config/locales/hyrax.en.yml
Labels: patch-ver

#2398 Fix 'basic theme' Appearance customization colors
  Gemfile
  Gemfile.lock
  app/assets/javascripts/admin_color_select.js
  app/assets/javascripts/admin_font_select.js
  app/assets/javascripts/application.js
  app/assets/javascripts/hyku/admin/appearance/colors.js
  app/assets/javascripts/hyku/admin/appearance/default_images.js
  app/assets/javascripts/hyku/admin/appearance/fonts.js
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/hyrax.scss
  app/assets/stylesheets/themes/cultural_repository.scss
  app/assets/stylesheets/themes/scholarly_show.scss
  app/assets/stylesheets/variables.scss
  app/forms/hyku/forms/admin/appearance.rb
  app/views/hyrax/admin/appearances/_banner_image_form.html.erb
  app/views/hyrax/base/_analytics_button.html.erb
  app/views/hyrax/base/show.html.erb
  app/views/hyrax/content_blocks/_form.html.erb
  app/views/hyrax/homepage/_featured_collection_section.html.erb
  app/views/hyrax/my/_collection_action_menu.html.erb
  app/views/hyrax/my/_work_action_menu.html.erb
  app/views/hyrax/oers/_form_metadata.html.erb
  app/views/shared/_appearance_styles.html.erb
  app/views/themes/cultural_repository/catalog/_search_form.html.erb
  app/views/themes/cultural_repository/hyrax/homepage/_featured_works.html.erb
  app/views/themes/institutional_repository/catalog/_search_form.html.erb
  app/views/themes/institutional_repository/layouts/hyrax.html.erb
  app/views/themes/neutral_repository/layouts/_share_your_work_row.html.erb
  config/initializers/simple_form_bootstrap.rb
  config/locales/en.yml
  config/locales/hyrax.en.yml
Labels: patch-ver

#2400 work_authorizations code is not in hyku yet, this schema change is an error
  db/schema.rb
Labels: ignore-for-release

#2395 fix guest lookup to be unscoped
  app/controllers/application_controller.rb
  app/controllers/devise_guest_controllers_helpers_decorator.rb
Labels: patch-ver

#2402 fix bulkrax file loader
  app/assets/javascripts/application.js
Labels: patch-ver

#2399 bootstrap 4 uses card instead of panel
  app/assets/stylesheets/application.css
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/themes/cultural_repository.scss
  app/views/admin/roles_service/index.html.erb
  app/views/hyrax/content_blocks/_form.html.erb
  app/views/hyrax/oers/show.html.erb
  app/views/roles/index.html.erb
  app/views/themes/cultural_repository/_facets.html.erb
  app/views/themes/image_show/hyrax/base/show.html.erb
  app/views/themes/scholarly_show/hyrax/oers/show.html.erb
Labels: patch-ver

#2403 Update Bulkrax to 9.0
  Gemfile
  Gemfile.lock
  db/schema.rb
Labels: minor-ver
