Repository samvera/hyku, pull requests merged in 2024-07, with the labels that each got.

#2261 i51 - reverts accidental delete
  app/views/hyrax/dashboard/collections/_form_share.html.erb
Labels: patch-ver

#2260 Hyku v6.0.0 release
  .env
  Gemfile
  Gemfile.lock
  app/models/concerns/hyrax/solr_document_behavior_decorator.rb
  config/initializers/riiif.rb
  ops/demo-deploy.tmpl.yaml
  ops/iiif-deploy.tmpl.yaml
  ops/iiif.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/services/iiif_print/tenant_config_spec.rb
  spec/tasks/migrate_hyku_commons_collection_thumbnails_to_valkyrie_spec.rb
  spec/tasks/rake_spec.rb
  spec/views/_user_util_links.html.erb_spec.rb
  spec/views/themes/cultural_repository/_user_util_links.html.erb_spec.rb
  spec/views/themes/institutional_repository/_user_util_links.html.erb_spec.rb
Labels: ignore-for-release

#2263 Styling updates
  Gemfile.lock
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/hyrax.scss
Labels: patch-ver

#2264 ✅ Fix QuickClassificationQuery leaky spec
  spec/services/hyrax/quick_classification_query_spec.rb
Labels: patch-ver

#2265 Version bump
  config/initializers/version.rb
Labels: major-ver

#2266 Styling updates
  Gemfile.lock
  app/assets/javascripts/stat_slider.js
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/themes/cultural_repository.scss
  app/assets/stylesheets/themes/cultural_show.scss
  app/assets/stylesheets/themes/institutional_repository.scss
  app/assets/stylesheets/themes/neutral_repository.scss
  app/assets/stylesheets/themes/scholarly_show.scss
  app/views/catalog/_index_header_list_collection.html.erb
  app/views/hyrax/homepage/_featured_collection_section.html.erb
  app/views/themes/cultural_repository/_masthead.html.erb
  app/views/themes/cultural_repository/catalog/_search_form.html.erb
  app/views/themes/cultural_repository/hyrax/homepage/_facet_layout.html.erb
  app/views/themes/cultural_repository/hyrax/homepage/_marketing.html.erb
  app/views/themes/cultural_repository/layouts/homepage.html.erb
  app/views/themes/institutional_repository/_masthead.html.erb
  app/views/themes/institutional_repository/catalog/_search_form.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_resource_type_slider.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_resource_type_stats.html.erb
  app/views/themes/institutional_repository/layouts/homepage.html.erb
  app/views/themes/neutral_repository/_featured_carousel.html.erb
  app/views/themes/neutral_repository/_theme_container.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_featured_works.html.erb
Labels: patch-ver
