Repository samvera/hyku, pull requests merged in 2025-03, with the labels that each got.

#2476 removes deprecated derived and is_derived
  app/indexers/hyku/indexers/file_set_indexer.rb
  app/models/file_set.rb
  app/models/hyrax/file_set_decorator.rb
  app/services/hyrax/work_uploads_handler_decorator.rb
  config/metadata/hyku_file_set_metadata.yaml
Labels: patch-ver

#2470 🎁 Marks Notifications as Read on Dashboard
  app/controllers/hyrax/notifications_controller_decorator.rb
  spec/controllers/hyrax/notifications_controller_spec.rb
Labels: patch-ver

#2481 Update hyrax for finding sipity entity
  Gemfile.lock
Labels: patch-ver

#2486 Fixes video embed viewer
  config/metadata/with_video_embed.yaml
Labels: patch-ver

#2487 Image Build and Docker Improvements
  .github/workflows/base.yaml
  .github/workflows/build-test-lint.yaml
  .github/workflows/build.yml
  .github/workflows/deploy.yaml
  .github/workflows/release.yml
  .github/workflows/verify_labels.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  bin/db-migrate-seed.sh
  bin/service-wait.sh
  bin/solrcloud-assign-configset.sh
  bin/solrcloud-upload-configset.sh
  config/environments/production.rb
  docker-compose.yml
  solr/Dockerfile
Labels: patch-ver

#2490 fixing migrations script
  bin/db-migrate-seed.sh
Labels: ignore-for-release

#2493 use the fits service for local dev
  .env
  Dockerfile
  docker-compose.yml
Labels: patch-ver

#2494 Get deploy action working again for repo
  .github/workflows/deploy.yaml
Labels: ignore-for-release

#2497 Add app bin dir to path to make accessing commands more convenient
  Dockerfile
  bin/bundle
  bin/web
  bin/worker
  docker-compose.yml
Labels: ignore-for-release

#2499 make the PATH part of the docker ENV
  Dockerfile
  docker-compose.yml
Labels: ignore-for-release

#2500 bring db wait back until hyrax is upgraded
  bin/db-wait.sh
Labels: ignore-for-release

#2503 ⬆️ Update WillowSword gem
  Gemfile.lock
Labels: minor-ver

#2504 ⚙️ Change default work model for WillowSword
  config/initializers/willow_sword.rb
Labels: minor-ver

#2505 🐛 Make analytics go away if it is not checked
  app/models/concerns/account_settings.rb
Labels: patch-ver

#2506 ⬆️ Update WillowSword gem
  Gemfile.lock
Labels: patch-ver

#2507 ⬆️ Update WillowSword gem
  Gemfile.lock
Labels: patch-ver

#2508 ⬆️ Update WillowSword gem
  Gemfile.lock
Labels: patch-ver
