Repository samvera/hyku, pull requests merged in 2025-04, with the labels that each got.

#2511 🚧 Based near 0 bug fix
  app/forms/based_near_form_fields_behavior.rb
  app/forms/etd_resource_form.rb
  app/forms/oer_resource_form.rb
Labels: ignore-for-release

#2513 Add base multiarch push
  .github/workflows/build-test-lint.yaml
Labels: ignore-for-release

#2514 add new home urls for demo and staging, add sponsor line to footer
  app/views/shared/_footer.html.erb
  ops/demo-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: ignore-for-release

#2516 rails doesn't let you have underscores in host names
  .env
Labels: ignore-for-release

#2518 Fix new proxy env
  .env
Labels: ignore-for-release

#2517 Update hyrax and bulkrax
  .dockerignore
  Gemfile.lock
  app/services/migrate_resource_service_decorator.rb
  spec/models/hyrax/file_set_decorator_spec.rb
  spec/models/hyrax/sipity_spec.rb
Labels: patch-ver

#2519 Hyrax update for queued indexing
  .env
  Dockerfile
  Gemfile.lock
  config/initializers/wings.rb
  docker-compose.yml
Labels: ignore-for-release

#2520 make index queues tenant aware and jobs auto schedule if redis queuin…
  .dockerignore
  .gitignore
  app/models/account.rb
  app/models/redis_endpoint.rb
Labels: ignore-for-release

#2523 rescue from key error if redis queue not found
  app/models/redis_endpoint.rb
Labels: ignore-for-release

#2524 ⬆️ Update WillowSword gem
  Gemfile.lock
Labels: patch-ver

#2525 ⬆️ Update Hyrax
  Gemfile.lock
Labels: patch-ver

#2528 Add custom query for IiifPrint
  app/services/hyrax/custom_queries/find_by_model_and_property_value.rb
  config/initializers/wings.rb
Labels: patch-ver

#2529 Fix advanced search
  lib/blacklight_advanced_search/advanced_query_parser_decorator.rb
Labels: patch-ver

#2530 Cache money
  .env
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/catalog_controller.rb
  app/controllers/concerns/hyku/works_controller_behavior.rb
  config/application.rb
  config/environments/staging.rb
  config/initializers/rack_attack.rb
  config/initializers/session_store.rb
  spec/rails_helper.rb
Labels: patch-ver

#2531 Rack attack settings from ENV
  config/initializers/rack_attack.rb
Labels: patch-ver

#2532 ⬆️ Update WillowSword
  Gemfile.lock
Labels: patch-ver

#2533 Favor snake case for class-based locale lookups
  app/helpers/application_helper.rb
Labels: patch-ver

#2536 fix redis for staging
  ops/staging-deploy.tmpl.yaml
Labels: ignore-for-release

#2537 Add Account setting to exclude chosen fields from search results page
  app/controllers/catalog_controller.rb
  app/models/concerns/account_settings.rb
  config/locales/de.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/hyrax.de.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/locales/it.yml
  config/locales/pt-BR.yml
  config/locales/simple_form.de.yml
  config/locales/simple_form.en.yml
  config/locales/simple_form.es.yml
  config/locales/simple_form.fr.yml
  config/locales/simple_form.it.yml
  config/locales/simple_form.pt-BR.yml
  config/locales/simple_form.zh.yml
  config/locales/zh.yml
  spec/models/concerns/account_settings_spec.rb
Labels: minor-ver

#2534 Only throttle `/catalog` requests
  config/initializers/rack_attack.rb
  ops/demo-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: patch-ver
