Repository samvera/hyku, pull requests merged in 2025-01, with the labels that each got.

#2405 :broom: renames scientst-softserv => notch8
  .github/workflows/base.yaml
  .github/workflows/build-test-lint.yaml
  .github/workflows/deploy.yaml
  Gemfile
  Gemfile.lock
  app/jobs/create_large_derivatives_job.rb
  app/models/sushi.rb
  app/models/sushi/platform_report.rb
  app/presenters/hyrax/collection_presenter_decorator.rb
  app/services/hyrax/work_uploads_handler_decorator.rb
  app/services/iiif_print/tenant_config.rb
  config/application.rb
  spec/controllers/hyrax/homepage_controller_spec.rb
  spec/features/feature_flag_spec.rb
Labels: ignore-for-release

#2406 Final appearance color fixes
  app/views/shared/_appearance_styles.html.erb
  app/views/shared/_footer.html.erb
  config/locales/en.yml
Labels: patch-ver

#2407 Fix member pagination on OER show pages
  app/views/hyrax/oers/_related_items.html.erb
  app/views/themes/cultural_show/hyrax/oers/_related_items.html.erb
Labels: patch-ver

#2409 🧹 Updates to search form overrides
  Gemfile.lock
  app/views/themes/cultural_repository/catalog/_search_form.html.erb
  app/views/themes/institutional_repository/catalog/_search_form.html.erb
Labels: patch-ver

#2410 ✅ Fix flaky work_show_presenter_spec
  spec/presenters/hyku/work_show_presenter_spec.rb
Labels: patch-ver

#2414 working on issues with bulkrax and hyrax javascript
  Gemfile.lock
  app/assets/javascripts/application.js
Labels: ignore-for-release

#2416 🧹 Adjust show pages
  app/assets/stylesheets/themes/cultural_show.scss
  app/views/themes/cultural_show/hyrax/base/_show_actions.html.erb
  app/views/themes/cultural_show/hyrax/base/_work_title.html.erb
  app/views/themes/cultural_show/hyrax/base/show.html.erb
  app/views/themes/scholarly_show/hyrax/base/_show_actions.html.erb
  app/views/themes/scholarly_show/hyrax/base/_work_title.html.erb
  app/views/themes/scholarly_show/hyrax/base/show.html.erb
  spec/services/create_account_spec.rb
Labels: patch-ver

#2419 🧹 Switch from bootstrap class to css
  app/assets/stylesheets/themes/cultural_show.scss
  app/views/themes/cultural_show/hyrax/base/show.html.erb
Labels: patch-ver

#2420 🧹 Fix catalog gallery view
  app/assets/stylesheets/hyku.scss
  app/controllers/catalog_controller.rb
  app/helpers/application_helper.rb
  app/views/shared/_appearance_styles.html.erb
Labels: patch-ver

#2421 update bulkrax to v9.0.2
  Gemfile.lock
Labels: ignore-for-release

#2425 Update Bulkrax
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2427 🐛 refresh CodeMirror editor when CSS tab is shown
  app/views/hyrax/admin/appearances/_custom_css_form.html.erb
Labels: patch-ver

#2423 Fix content blocks
  app/views/hyrax/content_blocks/_form.html.erb
  app/views/shared/_appearance_styles.html.erb
  config/locales/hyrax.en.yml
  spec/views/hyrax/content_blocks/edit.html.erb_spec.rb
Labels: patch-ver

#2428 Update bulkrax and add user stat importer decorator
  Gemfile.lock
  app/services/hyrax/user_stat_importer_decorator.rb
Labels: patch-ver

#2430 🧹 Clean up featured collection UI
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/themes/institutional_repository.scss
  app/views/hyrax/homepage/_explore_collections.html.erb
  app/views/hyrax/homepage/_featured_collection_fields.html.erb
  app/views/hyrax/homepage/_sortable_featured_collections.html.erb
  app/views/shared/_appearance_styles.html.erb
Labels: patch-ver

#2431 I189 institutional repository carousel
  app/assets/javascripts/stat_slider.js
  app/assets/stylesheets/themes/institutional_repository.scss
  app/views/themes/institutional_repository/hyrax/homepage/_resource_type_slider.html.erb
Labels: ignore-for-release

#2429 :gift: adds batch email, depositor email, and user stat to Account Settings
  app/models/account.rb
  app/models/concerns/account_settings.rb
  app/views/hyrax/dashboard/profiles/_edit_primary.html.erb
  app/views/hyrax/users/_user_info.html.erb
  spec/features/accounts_spec.rb
  spec/models/concerns/account_settings_spec.rb
  spec/services/create_account_spec.rb
Labels: minor-ver

#2432 Update IIIF Print
  Gemfile.lock
Labels: patch-ver

#2433 :bug: Fix contact form submission with negative captcha
  app/controllers/hyrax/contact_form_controller_decorator.rb
Labels: minor-ver

#2434 Update Bulkrax
  Gemfile.lock
Labels: patch-ver

#2436 🧹 Lock Hyrax to specific version
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
Labels: patch-ver

#2437 🧹 Remove Hyrax.config.analytics from the codebase
  app/views/hyrax/base/_analytics_button.html.erb
  app/views/hyrax/base/_show_actions.html.erb
  app/views/hyrax/base/show.html.erb
  app/views/hyrax/dashboard/sidebar/_activity.html.erb
  app/views/hyrax/oers/show.html.erb
  app/views/themes/cultural_show/hyrax/base/show.html.erb
  app/views/themes/cultural_show/hyrax/oers/show.html.erb
  app/views/themes/image_show/hyrax/base/show.html.erb
  app/views/themes/scholarly_show/hyrax/base/show.html.erb
  app/views/themes/scholarly_show/hyrax/oers/show.html.erb
Labels: patch-ver

#2438 Update IiifPrint Gem to v3.0.3
  Gemfile
  Gemfile.lock
Labels: patch-ver

#2442 ⬆️ Update Bulkrax
  Gemfile.lock
Labels: patch-ver

#2440 Add member methods on AdminSetResource
  app/models/admin_set_resource.rb
  spec/models/admin_set_resource_spec.rb
Labels: patch-ver

#2441 I117 pals vs pals knapsack comp
  app/parsers/bulkrax/csv_parser_decorator.rb
  lib/tasks/tenants.rake
Labels: patch-ver
