Repository samvera/hyku, pull requests merged in 2025-08, with the labels that each got.

#2633 🎁 Prevents removal of classes that have already-persisted records
  app/services/hyrax/flexible_schema_validator_service.rb
  app/services/hyrax/flexible_schema_validators/class_validator.rb
  app/services/hyrax/flexible_schema_validators/schema_validator.rb
  spec/services/hyrax/flexible_schema_validator_service_spec.rb
Labels: patch-ver

#2654 :bug: updates hyrax to pull in delete bug fix
  Gemfile.lock
Labels: patch-ver

#2651 :bug: Fix work type validation for Valkyrie object factory imports
  app/models/concerns/bulkrax/import_behavior_decorator.rb
Labels: ignore-for-release

#2669 🥳 hyrax base now has parity with the hyku base again!
  .github/workflows/build-test-lint.yaml
  .github/workflows/release.yml
  Dockerfile
  docker-compose.yml
Labels: minor-ver

#2670 Backport Base removal to 6.1
  .github/workflows/build-test-lint.yaml
  .github/workflows/release.yml
  Dockerfile
  docker-compose.yml
Labels: minor-ver

#2668 6.1 lightning round
  app/assets/stylesheets/hyku.scss
  app/views/hyrax/base/_form_share.html.erb
Labels: minor-ver

#2679 Update the bitnami-nginx image
  ops/iiif-deploy.tmpl.yaml
  ops/iiif.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: ignore-for-release

#2680 [i461] - Rework fix for collection forms
  Gemfile.lock
Labels: patch-ver

#2687 Add missing translations
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/hyrax.de.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/locales/it.yml
  config/locales/pt-BR.yml
  config/locales/zh.yml
Labels: patch-ver

#2686 Update Dockerfile to set bin script path
  Dockerfile
Labels: patch-ver

#2690 🎁 i892 exclude collections from catalog search
  app/forms/collection_resource_form.rb
  app/search_builders/adv_search_builder.rb
  app/views/hyrax/dashboard/collections/_form_discovery.html.erb
  config/locales/hyrax.en.yml
  config/metadata/collection_resource.yaml
  config/metadata_profiles/m3_profile.yaml
  spec/forms/collection_resource_form_spec.rb
  spec/indexers/collection_resource_indexer_spec.rb
  spec/models/collection_resource_spec.rb
  spec/search_builders/adv_search_builder_spec.rb
Labels: patch-ver

#2660 update-production-dc-file-links
  docker-compose.production.yml
Labels: ignore-for-release
