Repository samvera/hyku, pull requests merged in 2025-02, with the labels that each got.

#2439 I142 home page themes
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/themes/cultural_repository.scss
  app/assets/stylesheets/themes/institutional_repository.scss
  app/assets/stylesheets/themes/neutral_repository.scss
  app/views/_user_util_links.html.erb
  app/views/catalog/_search_form.html.erb
  app/views/hyrax/homepage/_explore_collections.html.erb
  app/views/hyrax/homepage/_home_content.html.erb
  app/views/shared/_footer.html.erb
  app/views/themes/cultural_repository/_facets.html.erb
  app/views/themes/cultural_repository/_masthead.html.erb
  app/views/themes/cultural_repository/_user_util_links.html.erb
  app/views/themes/cultural_repository/catalog/_search_form.html.erb
  app/views/themes/cultural_repository/layouts/homepage.html.erb
  app/views/themes/institutional_repository/_controls.html.erb
  app/views/themes/institutional_repository/_logo.html.erb
  app/views/themes/institutional_repository/_masthead.html.erb
  app/views/themes/neutral_repository/_theme_container.html.erb
  spec/features/institutional_repository_theme_spec.rb
Labels: ignore-for-release

#2444 Pitt account settings follow up
  app/models/concerns/account_settings.rb
  spec/models/concerns/account_settings_spec.rb
Labels: ignore-for-release

#2445 🐛 Ensure solr adapter on account switch
  app/models/solr_endpoint.rb
Labels: patch-ver

#2446 🐛 Add UV search params onto other gallery views
  app/helpers/hyku/blacklight_helper_behavior.rb
Labels: patch-ver

#2447 ⬆️ Update WillowSword gem
  Gemfile.lock
  config/initializers/hyrax.rb
  config/initializers/willow_sword.rb
Labels: patch-ver

#2448 Update hyrax, bulkrax, and iiif_print
  Gemfile.lock
Labels: patch-ver

#2449 Additional fixes based on issues found in Adventist
  Gemfile.lock
  app/assets/stylesheets/hyku.scss
  app/assets/stylesheets/hyrax.scss
  app/views/themes/cultural_show/hyrax/base/_work_title.html.erb
  app/views/themes/image_show/hyrax/base/_work_title.html.erb
  app/views/themes/scholarly_show/hyrax/base/_work_title.html.erb
Labels: patch-ver

#2450 🧹 Remove title from index and update translations
  app/controllers/catalog_controller.rb
  app/helpers/application_helper.rb
  config/locales/blacklight.de.yml
  config/locales/blacklight.en.yml
  config/locales/blacklight.es.yml
  config/locales/blacklight.fr.yml
  config/locales/blacklight.it.yml
  config/locales/blacklight.pt-BR.yml
  config/locales/blacklight.zh.yml
  config/locales/de.yml
  config/locales/en.yml
  config/locales/es.yml
  config/locales/fr.yml
  config/locales/hyrax.de.yml
  config/locales/hyrax.es.yml
  config/locales/hyrax.fr.yml
  config/locales/hyrax.it.yml
  config/locales/hyrax.pt-BR.yml
  config/locales/hyrax.zh.yml
  config/locales/it.yml
  config/locales/pt-BR.yml
  config/locales/zh.yml
Labels: patch-ver

#2454 Adds appearance color options
  app/assets/stylesheets/hyku.scss
  app/forms/hyku/forms/admin/appearance.rb
  app/views/shared/_appearance_styles.html.erb
  config/locales/en.yml
  config/locales/hyrax.en.yml
Labels: patch-ver

#2456 Allow for theme color defaults
  app/assets/javascripts/hyku/admin/appearance/colors.js
  app/forms/hyku/forms/admin/appearance.rb
  app/views/hyrax/admin/appearances/_default_colors_form.html.erb
  config/home_themes.yml
Labels: patch-ver

#2453 I194 google analytics
  .github/workflows/deploy.yaml
  Gemfile.lock
  app/jobs/user_stat_collection_job.rb
  app/models/concerns/account_settings.rb
  app/models/hyrax/statistic_decorator.rb
  app/services/hyrax/user_stat_importer_decorator.rb
  app/views/shared/_ga4.html.erb
  config/locales/simple_form.en.yml
  ops/demo-deploy.tmpl.yaml
  spec/jobs/user_stat_collection_job_spec.rb
  spec/models/concerns/account_settings_spec.rb
  spec/rails_helper.rb
Labels: patch-ver

#2458 I1019 batch email notifications
  app/jobs/batch_email_notification_job.rb
  spec/factories/mailboxer_messages.rb
  spec/jobs/batch_email_notification_job_spec.rb
  spec/rails_helper.rb
Labels: ignore-for-release

#2460 i240 home page layout on neutral and cultural theme
  app/assets/stylesheets/themes/institutional_repository.scss
  app/views/hyrax/homepage/_featured_collection_section.html.erb
  app/views/themes/institutional_repository/hyrax/homepage/_resource_type_stats.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_explore_collections.html.erb
  app/views/themes/neutral_repository/hyrax/homepage/_featured_works.html.erb
Labels: ignore-for-release

#2461 🐛 Fix re-split for PDFs
  app/services/iiif_print/tenant_config.rb
Labels: patch-ver

#2457 Switch from Sidekiq to GoodJob as the Default Worker
  .env
  ops/demo-deploy.tmpl.yaml
  ops/iiif-deploy.tmpl.yaml
  ops/iiif.tmpl.yaml
  ops/review-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: minor-ver

#2463 Ga4 follow up
  Gemfile.lock
  app/models/concerns/account_settings.rb
Labels: patch-ver

#2465 🐛 Standardize carousel container dimensions
  app/assets/stylesheets/themes/neutral_repository.scss
  app/views/themes/neutral_repository/_featured_carousel.html.erb
Labels: ignore-for-release

#2468 ⬆️ Update Hyrax and WillowSword
  Gemfile.lock
Labels: patch-ver

#2469 rework user_analytics setting
  app/models/account.rb
  app/models/concerns/account_settings.rb
  config/locales/simple_form.en.yml
  spec/models/account_spec.rb
  spec/models/concerns/account_settings_spec.rb
  spec/services/create_account_spec.rb
Labels: patch-ver

#2472 Remove unneeded decorator
  app/models/concerns/hyrax/solr_document_behavior_decorator.rb
Labels: patch-ver

#2471 Fix sipity with migrations
  app/models/sipity.rb
  app/services/migrate_resource_service_decorator.rb
  spec/features/work_show_institution_visibility_spec.rb
  spec/features/work_show_open_visibility_spec.rb
  spec/features/work_show_private_visibility_spec.rb
  spec/models/hyrax/sipity_spec.rb
Labels: bug, patch-ver

#2474 update Bulkrax
  Gemfile.lock
Labels: patch-ver
