Repository samvera/hyku, pull requests merged in 2025-07, with the labels that each got.

#2612 ⚙️ Updating Hyrax to the latest commit
  Gemfile.lock
Labels: bug, patch-ver

#2615 bumps hyrax version for chunk upload fix
  Gemfile.lock
Labels: ignore-for-release

#2617 I29 m3 validator
  Gemfile
  Gemfile.lock
  app/models/hyrax/flexible_schema_decorator.rb
  app/services/hyrax/core_metadata_validator.rb
  app/services/hyrax/flexible_schema_validator_service.rb
  config/metadata_profiles/m3_profile.yaml
  lib/flexible/m3_json_schema.json
  spec/fixtures/files/m3_profile.yaml
  spec/services/hyrax/core_metadata_validator_spec.rb
  spec/services/hyrax/flexible_schema_validator_service_spec.rb
Labels: patch-ver

#2621 :bug: rescue google permission denied error
  app/models/concerns/account_settings.rb
  app/views/hyrax/dashboard/_user_activity.html.erb
Labels: patch-ver

#2624 update-redis-in-deploys
  ops/demo-deploy.tmpl.yaml
  ops/iiif-deploy.tmpl.yaml
  ops/staging-deploy.tmpl.yaml
Labels: ignore-for-release

#2628 I429 profile defines available work types
  app/controllers/admin/work_types_controller.rb
  app/services/hyrax/flexible_schema_validator_service.rb
  app/services/hyrax/quick_classification_query_decorator.rb
  app/views/admin/work_types/edit.html.erb
  spec/services/hyrax/flexible_schema_validator_service_spec.rb
Labels: patch-ver

#2627 I425 validation clean up
  Gemfile.lock
  app/controllers/admin/work_types_controller.rb
  app/services/hyrax/core_metadata_validator.rb
  app/services/hyrax/flexible_schema_validator_service.rb
  app/services/hyrax/quick_classification_query_decorator.rb
  app/views/admin/work_types/edit.html.erb
  app/views/hyrax/base/_work_description.erb
  config/metadata_profiles/m3_profile.yaml
  lib/flexible/m3_json_schema.json
  spec/fixtures/files/m3_profile.yaml
  spec/services/hyrax/core_metadata_validator_spec.rb
  spec/services/hyrax/flexible_schema_validator_service_spec.rb
Labels: patch-ver

#2631 🐛 A/V was not loading correctly
  app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb
  config/application.rb
  spec/config/application_spec.rb
Labels: patch-ver

#2630 Handles error gracefully when worktype isn't configured
  app/factories/bulkrax/object_factory_interface_decorator.rb
Labels: minor-ver

#2638 Updates hyrax
  Gemfile.lock
Labels: ignore-for-release
